name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        permissions: write-all
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
            -   name: Submit Dependency Snapshot
                uses: advanced-security/maven-dependency-submission-action@v3
                
            -   name: Cache Maven packages
                uses: actions/cache@v3.3.1
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2-
                    
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: "java-kotlin"
                
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
        
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
